/* ARCHIVO GENERADO AUTOMÁTICAMENTE — NO EDITAR A MANO */
const biblioteca = [
  {"codigo":"DR000002","titulo":"2gether","pais":["TH"],"anio":2020,"tipo":"Drama","temporada":1,"estado":"Finalizado","activo":true,"numEspeciales":2,"tieneSinopsis":true,"tieneOrigen":false,"tienePersonas":true,"tieneEntidades":true,"tieneMultimedia":true,"tieneFranquicia":true,"tieneUniverso":false,"tieneSerie":true,"tieneRemake":false,"portada":"https://upload.wikimedia.org/wikipedia/en/6/68/2gether_The_Series_2020_poster.jpg","ship":"BrightWin","numShips":3},
  {"codigo":"DR000003","titulo":"Still 2gether","pais":["TH"],"anio":2020,"tipo":"Drama","temporada":2,"estado":"Finalizado","activo":true,"numEspeciales":1,"tieneSinopsis":true,"tieneOrigen":false,"tienePersonas":true,"tieneEntidades":true,"tieneMultimedia":true,"tieneFranquicia":true,"tieneUniverso":false,"tieneSerie":true,"tieneRemake":false,"portada":"https://image.tmdb.org/t/p/original/4aZ2P5crezp0Kl4E4VUJQRO362T.jpg","ship":"BrightWin","numShips":3},
  {"codigo":"DR000005","titulo":"The Eighth Sense","pais":["KR"],"anio":2023,"tipo":"Drama","temporada":1,"estado":"Finalizado","activo":true,"numEspeciales":0,"tieneSinopsis":true,"tieneOrigen":false,"tienePersonas":true,"tieneEntidades":true,"tieneMultimedia":true,"tieneFranquicia":true,"tieneUniverso":false,"tieneSerie":false,"tieneRemake":false,"portada":"https://i.pinimg.com/736x/bf/ca/06/bfca06960028fb349da11263aa5ab04c.jpg","ship":"Im Ji & Oh Jun","numShips":1},
  {"codigo":"DR000839","titulo":"7 Project","pais":["TH"],"anio":2021,"tipo":"Antología","temporada":1,"estado":"Finalizado","activo":true,"numEspeciales":0,"tieneSinopsis":true,"tieneOrigen":false,"tienePersonas":false,"tieneEntidades":false,"tieneMultimedia":false,"tieneFranquicia":false,"tieneUniverso":false,"tieneSerie":false,"tieneRemake":false},
  {"codigo":"DR000939","titulo":"Fourever You","pais":["TH"],"anio":2024,"tipo":"Drama","temporada":1,"estado":"Finalizado","activo":true,"numEspeciales":2,"tieneSinopsis":true,"tieneOrigen":true,"tienePersonas":false,"tieneEntidades":false,"tieneMultimedia":false,"tieneFranquicia":true,"tieneUniverso":false,"tieneSerie":false,"tieneRemake":false},
  {"codigo":"DR001016","titulo":"My Secret of Seer","pais":["TH"],"anio":2025,"tipo":"Serie","temporada":1,"estado":"Finalizado","activo":true,"numEspeciales":0,"tieneSinopsis":true,"tieneOrigen":true,"tienePersonas":false,"tieneEntidades":false,"tieneMultimedia":false,"tieneFranquicia":false,"tieneUniverso":false,"tieneSerie":false,"tieneRemake":false}
];
