/* ======================================================
   Asian Stories Library   ENTIDADES.js   
====================================================== */
const ENTIDADES = [
  { codigo: 'EN000001', nombre: 'TV Tokyo', pais: 'JP', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000002', nombre: 'Stardust Pictures', pais: 'JP', tipos: ['Productora'], activo: true },
  { codigo: 'EN000003', nombre: 'Moonlight ENT', pais: 'KR', tipos: ['Productora'], activo: true },
  { codigo: 'EN000004', nombre: 'GMMTV', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000005', nombre: 'Housestories 8', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000006', nombre: 'GMM 25', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000007', nombre: 'The One Enterprise', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000008', nombre: 'TV Thunder', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000009', nombre: 'PPTV HD 36', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000010', nombre: 'Studio Wabi Sabi', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000011', nombre: 'Me Mind Y', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000012', nombre: 'Felloww', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000013', nombre: 'Bear House Production', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000014', nombre: 'One 31', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000015', nombre: 'GMM Grammy', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000016', nombre: 'Asmik Ace', pais: 'JP', tipos: ['Distribuidora'], activo: true },
  { codigo: 'EN000017', nombre: 'Golden Village Pictures', pais: 'SG', tipos: ['Distribuidora'], activo: true },
  { codigo: 'EN000018', nombre: 'M Pictures Cambodia', pais: 'KH', tipos: ['Distribuidora'], activo: true },
  { codigo: 'EN000019', nombre: 'Vidol', pais: 'TW', tipos: ['Productora', 'Plataforma'], activo: true },
  { codigo: 'EN000020', nombre: 'SETTV', pais: 'TW', tipos: ['Productora', 'Emisora'], activo: true },
  { codigo: 'EN000021', nombre: 'SPO Entertainment', pais: 'TW', tipos: ['Productora'], activo: true },
  { codigo: 'EN000022', nombre: 'LINE TV', pais: 'TH', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000023', nombre: 'YouTube', pais: 'US', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000024', nombre: 'iQIYI', pais: 'CN', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000025', nombre: 'GagaOOLala', pais: 'TW', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000026', nombre: 'Disney+ Hotstar', pais: 'US', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000027', nombre: 'iWantTFC', pais: 'PH', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000028', nombre: 'Viki', pais: 'US', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000029', nombre: 'WeTV', pais: 'CN', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000030', nombre: 'SHORYUKEN Production', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000031', nombre: 'Viu', pais: 'HK', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000032', nombre: 'Ultimate Troop', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000033', nombre: 'Amarin TV', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000034', nombre: 'BEC World', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000035', nombre: 'Mediaplex International', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000036', nombre: 'Quality Plus Group', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000037', nombre: 'Channel 3', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000038', nombre: 'Argentis Studios', pais: 'TH', tipos: ['Productora'], activo: true },
   { codigo: 'EN000039', nombre: 'CHANGE2561', pais: 'TH', tipos: ['Productora'], activo: true },
{ codigo: 'EN000040', nombre: 'Netflix', pais: 'US', tipos: ['Plataforma'], activo: true },
{ codigo: 'EN000041', nombre: 'oneD', pais: 'TH', tipos: ['Plataforma'], activo: true },
{ codigo: 'EN000042', nombre: 'Maker-Y', pais: 'TH', tipos: ['Productora'], activo: true },
{ codigo: 'EN000043', nombre: 'Mandee Work', pais: 'TH', tipos: ['Productora'], activo: true },

{ codigo: 'EN000044', nombre: 'Workpoint TV', pais: 'TH', tipos: ['Emisora'], activo: true },
{ codigo: 'EN000045', nombre: 'Punphap Studio', pais: 'TH', tipos: ['Productora'], activo: true },

   { codigo: 'EN000046', nombre: 'Kongthup Production', pais: 'TH', tipos: ['Productora'], activo: true },
{ codigo: 'EN000047', nombre: 'Domundi TV', pais: 'TH', tipos: ['Productora'], activo: true },
{ codigo: 'EN000048', nombre: 'Copy A Bangkok', pais: 'TH', tipos: ['Productora'], activo: true },
   { codigo: 'EN000049', nombre: 'TrueVisions Now', pais: 'TH', tipos: ['Emisora'], activo: true },
{codigo:'EN000050', nombre:'GMO Films', pais:'TH', tipos:['Productora'], activo:true},
{codigo:'EN000051', nombre:'TV Asahi', pais:'JP', tipos:['Productora'], activo:true},
{codigo:'EN000052', nombre:'Cholumpi Brothers', pais:'TH', tipos:['Productora'], activo:true},
   { codigo: 'EN000053', nombre: 'Gemmistry Studio', pais: 'TH', tipos: ['Productora'], activo: true },
{ codigo:'EN000054', nombre:'AIS PLAY', pais:'TH', tipos:['Plataforma'], activo:true },
{ codigo:'EN000055', nombre:'Parbdee Taweesuk', pais:'TH', tipos:['Productora'], activo:true },
{ codigo:'EN000056', nombre:'Chamade Film', pais:'TH', tipos:['Productora'], activo:true },
   { codigo:'EN000057', nombre:'W-STORY', pais:'KR', tipos:['Productora'], activo:true },
{codigo:'EN000058', nombre:'EnergeDic Company', pais:'KR', tipos:['Productora'], activo:true},
{ codigo:'EN000059', nombre:'Contents Monster', pais:'KR', tipos:['Productora'], activo:true },
{ codigo:'EN000060', nombre:'Emotion Studio', pais:'KR', tipos:['Productora'], activo:true },
{ codigo:'EN000061', nombre:'Moving Pictures Co.', pais:'KR', tipos:['Productora'], activo:true },
{ codigo:'EN000062', nombre:'Idol Romance', pais:'KR', tipos:['Productora','Plataforma'], activo:true },
{ codigo:'EN000063', nombre:'Storywiz', pais:'KR', tipos:['Productora'], activo:true },
{ codigo:'EN000064', nombre:'Convergence TV', pais:'KR', tipos:['Productora'], activo:true },
{ codigo:'EN000065', nombre:'Japangi', pais:'KR', tipos:['Productora'], activo:true },
   {codigo:'EN000066', nombre:'H&Co', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000067', nombre:'Damhwa Co., Ltd.', pais:'KR', tipos:['Productora','Distribuidora'], activo:true},
{codigo:'EN000068', nombre:'Kiwi Media Group', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000069', nombre:'Jaye Entertainment', pais:'KR', tipos:['Distribuidora'], activo:true},
{codigo:'EN000070', nombre:'Bucket Studio', pais:'KR', tipos:['Distribuidora'], activo:true},
{codigo:'EN000071', nombre:'WHYNOT MEDIA', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000072', nombre:'Hanyang Studio', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000073', nombre:'SILKWOOD', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000074', nombre:'Little Big Pictures', pais:'KR', tipos:['Distribuidora'], activo:true},
{codigo:'EN000075', nombre:'ATA Entertainment', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000076', nombre:'Bilibili', pais:'CN', tipos:['Plataforma'], activo:true},
{codigo:'EN000077', nombre:'Sunset Studio', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000078', nombre:'RaemongRaein', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000079', nombre:'Axis', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000080', nombre:'Kakao TV', pais:'KR', tipos:['Productora','Plataforma'], activo:true},
{codigo:'EN000081', nombre:'Vanilla Production', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000082', nombre:'Another Pictures', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000083', nombre:'Media Atlantis', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000084', nombre:'Studio Yanggwibi', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000085', nombre:'Matchbox', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000086', nombre:'Strongberry', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000087', nombre:'The Dramatist', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000088', nombre:'Kidari Studio', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000089', nombre:'Watcha', pais:'KR', tipos:['Plataforma'], activo:true},
{codigo:'EN000090', nombre:'Rakuten TV', pais:'JP', tipos:['Plataforma'], activo:true},
{codigo:'EN000091', nombre:'Wavve', pais:'KR', tipos:['Plataforma'], activo:true},
{codigo:'EN000092', nombre:'Channel K', pais:'IN', tipos:['Plataforma'], activo:true},
{codigo:'EN000093', nombre:'ABEMA', pais:'JP', tipos:['Plataforma'], activo:true},
{codigo:'EN000094', nombre:'Box Media', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000095', nombre:'Kenaz', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000096', nombre:'T2N Media', pais:'KR', tipos:['Productora'], activo:true},
{codigo:'EN000097', nombre:'Youth Film', pais:'KR', tipos:['Productora'], activo:true},   
];
