/* ======================================================
   Asian Stories Library   ENTIDADES.js   
====================================================== */
const ENTIDADES = [
  { codigo: 'EN000001', nombre: 'TV Tokyo', pais: 'JP', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000002', nombre: 'Stardust Pictures', pais: 'JP', tipos: ['Productora'], activo: true },
  { codigo: 'EN000003', nombre: 'Moonlight ENT', pais: 'KR', tipos: ['Productora'], activo: true },
  { codigo: 'EN000004', nombre: 'GMMTV', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000005', nombre: 'Housestories 8', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000006', nombre: 'GMM 25', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000007', nombre: 'The One Enterprise', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000008', nombre: 'TV Thunder', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000009', nombre: 'PPTV HD 36', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000010', nombre: 'Studio Wabi Sabi', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000011', nombre: 'Me Mind Y', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000012', nombre: 'Felloww', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000013', nombre: 'Bear House Production', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000014', nombre: 'One 31', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000015', nombre: 'GMM Grammy', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000016', nombre: 'Asmik Ace', pais: 'JP', tipos: ['Distribuidora'], activo: true },
  { codigo: 'EN000017', nombre: 'Golden Village Pictures', pais: 'SG', tipos: ['Distribuidora'], activo: true },
  { codigo: 'EN000018', nombre: 'M Pictures Cambodia', pais: 'KH', tipos: ['Distribuidora'], activo: true },
  { codigo: 'EN000019', nombre: 'Vidol', pais: 'TW', tipos: ['Productora', 'Plataforma'], activo: true },
  { codigo: 'EN000020', nombre: 'SETTV', pais: 'TW', tipos: ['Productora', 'Emisora'], activo: true },
  { codigo: 'EN000021', nombre: 'SPO Entertainment', pais: 'TW', tipos: ['Productora'], activo: true },
  { codigo: 'EN000022', nombre: 'LINE TV', pais: 'TH', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000023', nombre: 'YouTube', pais: 'US', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000024', nombre: 'iQIYI', pais: 'CN', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000025', nombre: 'GagaOOLala', pais: 'TW', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000026', nombre: 'Disney+ Hotstar', pais: 'US', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000027', nombre: 'iWantTFC', pais: 'PH', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000028', nombre: 'Viki', pais: 'US', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000029', nombre: 'WeTV', pais: 'CN', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000030', nombre: 'SHORYUKEN Production', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000031', nombre: 'Viu', pais: 'HK', tipos: ['Plataforma'], activo: true },
  { codigo: 'EN000032', nombre: 'Ultimate Troop', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000033', nombre: 'Amarin TV', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000034', nombre: 'BEC World', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000035', nombre: 'Mediaplex International', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000036', nombre: 'Quality Plus Group', pais: 'TH', tipos: ['Productora'], activo: true },
  { codigo: 'EN000037', nombre: 'Channel 3', pais: 'TH', tipos: ['Emisora'], activo: true },
  { codigo: 'EN000038', nombre: 'Argentis Studios', pais: 'TH', tipos: ['Productora'], activo: true },
   { codigo: 'EN000039', nombre: 'CHANGE2561', pais: 'TH', tipos: ['Productora'], activo: true },
{ codigo: 'EN000040', nombre: 'Netflix', pais: 'US', tipos: ['Plataforma'], activo: true },
{ codigo: 'EN000041', nombre: 'oneD', pais: 'TH', tipos: ['Plataforma'], activo: true },
{ codigo: 'EN000042', nombre: 'Maker-Y', pais: 'TH', tipos: ['Productora'], activo: true },
{ codigo: 'EN000043', nombre: 'Mandee Work', pais: 'TH', tipos: ['Productora'], activo: true },

{ codigo: 'EN000044', nombre: 'Workpoint TV', pais: 'TH', tipos: ['Emisora'], activo: true },
{ codigo: 'EN000045', nombre: 'Punphap Studio', pais: 'TH', tipos: ['Productora'], activo: true },

];
