/* ======================================================
   Asian Stories Library   PERSONAS.js   
====================================================== */
const PERSONAS = [
  {codigo:'PR000001', nombre:'Shunsuke Kazama', alias:[], pais:'JP', profesiones:['Actor'], multimedia:{foto:'PR000001.webp'}, activo:true},
  {codigo:'PR000002', nombre:'Kohei Shoji', alias:[], pais:'JP', profesiones:['Actor'], multimedia:{foto:'PR000002.webp'}, activo:true},
  {codigo:'PR000003', nombre:'Amon Hirai', alias:[], pais:'JP', profesiones:['Actor'], multimedia:{foto:'PR000003.webp'}, activo:true},
  {codigo:'PR000004', nombre:'Riko Takayama', alias:[], pais:'JP', profesiones:['Actor'], multimedia:{foto:'PR000004.webp'}, activo:true},
  {codigo:'PR000005', nombre:'Keisuke Watanabe', alias:[], pais:'JP', profesiones:['Actor'], multimedia:{foto:'PR000005.webp'}, activo:true},
  {codigo:'PR000006', nombre:'Chihiro Ikeda', alias:[], pais:'JP', profesiones:['Director'], multimedia:{foto:'PR000006.webp'}, activo:true},
  {codigo:'PR000007', nombre:'Noriyoshi Kosuge', alias:[], pais:'JP', profesiones:['Director'], multimedia:{foto:'PR000007.webp'}, activo:true},
  {codigo:'PR000008', nombre:'Bright Vachirawit Chivaaree', alias:['Bright'], pais:'TH', profesiones:['Actor','Cantante'], multimedia:{foto:'PR000008.webp'}, activo:true},
  {codigo:'PR000009', nombre:'Win Metawin Opas-iamkajorn', alias:['Win'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000009.webp'}, activo:true},
  {codigo:'PR000010', nombre:'Gun Korawit Boonsri', alias:['Gun'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000010.webp'}, activo:true},
  {codigo:'PR000011', nombre:'Mike Chinnarat Siriphongchawalit', alias:['Mike'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000011.webp'}, activo:true},
  {codigo:'PR000012', nombre:'Frank Thanatsaran Samthonglai', alias:['Frank'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000012.webp'}, activo:true},
  {codigo:'PR000013', nombre:'Drake Sattabut Laedeke', alias:['Drake'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000013.webp'}, activo:true},
  {codigo:'PR000014', nombre:'Weerachit Thongjila', alias:[], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000014.webp'}, activo:true},
  {codigo:'PR000015', nombre:'Pratchaya Thavornthummarut', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000015.webp'}, activo:true},
  {codigo:'PR000016', nombre:'Toptap Jirakit Kuariyakul', alias:['Toptap'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000016.webp'}, activo:true},
  {codigo:'PR000017', nombre:'Khaotung Thanawat Rattanakitpaisan', alias:['Khaotung'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000017.webp'}, activo:true},
  {codigo:'PR000018', nombre:'Chayakorn Jutamas', alias:['JJ'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000018.webp'}, activo:true},
  {codigo:'PR000019', nombre:'Chanagun Arpornsutinan', alias:['Gunsmile'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000019.webp'}, activo:true},
  {codigo:'PR000020', nombre:'Sivakorn Lertchuchot', alias:['Guy'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000020.webp'}, activo:true},
  {codigo:'PR000021', nombre:'Ployphach Phatchatorn Thanawat', alias:['Ploy'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000021.webp'}, activo:true},
  {codigo:'PR000022', nombre:'Neen Suwanamas', alias:['Neen'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000022.webp'}, activo:true},
  {codigo:'PR000023', nombre:'Im Ji Sub', alias:[], pais:'KR', profesiones:['Actor'], multimedia:{foto:'PR000023.webp'}, activo:true},
  {codigo:'PR000024', nombre:'Oh Jun Taek', alias:[], pais:'KR', profesiones:['Actor'], multimedia:{foto:'PR000024.webp'}, activo:true},
  {codigo:'PR000025', nombre:'Lee Mi Ra', alias:[], pais:'KR', profesiones:['Actor'], multimedia:{foto:'PR000025.webp'}, activo:true},
  {codigo:'PR000026', nombre:'Yoon Se Bin', alias:[], pais:'KR', profesiones:['Actor'], multimedia:{foto:'PR000026.webp'}, activo:true},
  {codigo:'PR000027', nombre:'Geum Seong Ho', alias:[], pais:'KR', profesiones:['Actor'], multimedia:{foto:'PR000027.webp'}, activo:true},
  {codigo:'PR000028', nombre:'Weronika Tofilska', alias:[], pais:'KR', profesiones:['Director','Guionista'], multimedia:{foto:'PR000028.webp'}, activo:true},
  {codigo:'PR000029', nombre:'Pannut Wongwajrakamol', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000029.webp'}, activo:true},
  {codigo:'PR000030', nombre:'Tul Pakorn Thanasrivanitchai', alias:['Tul'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000030.webp'}, activo:true},
  {codigo:'PR000031', nombre:'Max Nattapol Diloknawarit', alias:['Max'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000031.webp'}, activo:true},
  {codigo:'PR000032', nombre:'Visava Thaiyanont', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000032.webp'}, activo:true},
  {codigo:'PR000033', nombre:'Pimnitchakun Bumrungkit', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000033.webp'}, activo:true},
  {codigo:'PR000034', nombre:'Simon Kessler', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000034.webp'}, activo:true},
  {codigo:'PR000035', nombre:'Janistar Phomphadungcheep', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000035.webp'}, activo:true},
  {codigo:'PR000036', nombre:'Satida Pinsinchai', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000036.webp'}, activo:true},
  {codigo:'PR000037', nombre:'Apiwat Porsche Apiwatsayree', alias:['Porsche'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000037.webp'}, activo:true},
  {codigo:'PR000038', nombre:'Olive Chiwpreecha Thitichaya', alias:['Olive'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000038.webp'}, activo:true},
  {codigo:'PR000039', nombre:'Sukonthawa Koetnimit', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000039.webp'}, activo:true},
  {codigo:'PR000040', nombre:'Supawit Tantimaporn', alias:['Farm'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000040.webp'}, activo:true},
  {codigo:'PR000041', nombre:'Khamphee Noomnoi', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000041.webp'}, activo:true},
  {codigo:'PR000042', nombre:'Tripobphoom Suthaphong', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000042.webp'}, activo:true},
  {codigo:'PR000043', nombre:'Sira Patrat', alias:['Yai'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000043.webp'}, activo:true},
  {codigo:'PR000044', nombre:'Thames Sanpakit', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000044.webp'}, activo:true},
  {codigo:'PR000045', nombre:'Kamonporn Kosriyakwong', alias:['NewNew'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000045.webp'}, activo:true},
  {codigo:'PR000046', nombre:'Jiratpisit Jarawijit', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000046.webp'}, activo:true},
  {codigo:'PR000047', nombre:'Tharanya Manoleehakol', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000047.webp'}, activo:true},
  {codigo:'PR000048', nombre:'Mikala Hazelwood', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000048.webp'}, activo:true},
  {codigo:'PR000049', nombre:'Thanaporn Rattanasasiwimon', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000049.webp'}, activo:true},
  {codigo:'PR000050', nombre:'Theekapat Chanwittayapong', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000050.webp'}, activo:true},
  {codigo:'PR000051', nombre:'Petei Hokari', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000051.webp'}, activo:true},
  {codigo:'PR000052', nombre:'Dome Jade Bunyoprakarn', alias:['Jade Bunyoprakarn'], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000052.webp'}, activo:true},
  {codigo:'PR000053', nombre:'Jaruporn Kamtornnoppakun', alias:[], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000053.webp'}, activo:true},
  {codigo:'PR000054', nombre:'Natouch Siripongthon', alias:['Fluke'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000054.webp'}, activo:true},
  {codigo:'PR000055', nombre:'Thitiwat Ritprasert', alias:['Ohm'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000055.webp'}, activo:true},
  {codigo:'PR000056', nombre:'Katsamonnat Namwirote', alias:['Earth'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000056.webp'}, activo:true},
  {codigo:'PR000057', nombre:'Noppakao Dechaphatthanakun', alias:['Kao'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000057.webp'}, activo:true},
  {codigo:'PR000058', nombre:'Warut Chawalitrujiwong', alias:['Prem'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000058.webp'}, activo:true},
  {codigo:'PR000059', nombre:'Noppanut Guntachai', alias:['Boun'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000059.webp'}, activo:true},
  {codigo:'PR000060', nombre:'Samantha Melanie Coates', alias:['Sammy'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000060.webp'}, activo:true},
  {codigo:'PR000061', nombre:'Pannin Charnmanoon', alias:['Pineare'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000061.webp'}, activo:true},
  {codigo:'PR000062', nombre:'Suphadach Wilairat', alias:['Bosston'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000062.webp'}, activo:true},
  {codigo:'PR000063', nombre:'Wanut Sangtianprapai', alias:['Mix'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000063.webp'}, activo:true},
  {codigo:'PR000064', nombre:'Phachara Suansri', alias:['Ja'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000064.webp'}, activo:true},
  {codigo:'PR000065', nombre:'Naphat Vikairungroj', alias:['Na'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000065.webp'}, activo:true},
  {codigo:'PR000066', nombre:'Phiravich Attachitsataporn', alias:['Mean'], pais:'TH', profesiones:['Actor','Director'], multimedia:{foto:'PR000066.webp'}, activo:true},
  {codigo:'PR000067', nombre:'Patsit Permpoonsavat', alias:['Yacht'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000067.webp'}, activo:true},
  {codigo:'PR000068', nombre:'Vittawin Veeravidhayanant', alias:['Best'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000068.webp'}, activo:true},
  {codigo:'PR000069', nombre:'Weerapat Toemmaneerat', alias:['Tae'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000069.webp'}, activo:true},
  {codigo:'PR000070', nombre:'Pakpoom Juanchainat', alias:['Art'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000070.webp'}, activo:true},
  {codigo:'PR000071', nombre:'Pakphum Jitpisutsiri', alias:['Ryu'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000071.webp'}, activo:true},
  {codigo:'PR000072', nombre:'Puwanai Sangwan', alias:['O'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000072.webp'}, activo:true},
  {codigo:'PR000073', nombre:'Pongsapak Oudompoch', alias:['Santa'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000073.webp'}, activo:true},
  {codigo:'PR000074', nombre:'Panupun Vongjorn', alias:['Benz'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000074.webp'}, activo:true},
  {codigo:'PR000075', nombre:'Siwaj Sawatmaneekul', alias:['New'], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000075.webp'}, activo:true},
  {codigo:'PR000076', nombre:'Inthira Thanasarnsumrit', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000076.webp'}, activo:true},
  {codigo:'PR000077', nombre:'Hong Wei-Zhe', alias:['Waji'], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000077.webp'}, activo:true},
  {codigo:'PR000078', nombre:'Yang Yi-Hsuan', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000078.webp'}, activo:true},
  {codigo:'PR000079', nombre:'Chen Jing-Xin', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000079.webp'}, activo:true},
  {codigo:'PR000080', nombre:'Hsia Yu-Ho', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000080.webp'}, activo:true},
  {codigo:'PR000081', nombre:'Wei-Po Liao', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000081.webp'}, activo:true},
  {codigo:'PR000082', nombre:'Hsu Po-Wei', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000082.webp'}, activo:true},
  {codigo:'PR000083', nombre:'Kevin Chang', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000083.webp'}, activo:true},
  {codigo:'PR000084', nombre:'Mao Chi-Sheng', alias:['Ba Ba Luo'], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000084.webp'}, activo:true},
  {codigo:'PR000085', nombre:'Hsiao Hung', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000085.webp'}, activo:true},
  {codigo:'PR000086', nombre:'Sun Ching-Yueh', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000086.webp'}, activo:true},
  {codigo:'PR000087', nombre:'Hong Shi', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000087.webp'}, activo:true},
  {codigo:'PR000088', nombre:'Yuan Lin', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000088.webp'}, activo:true},
  {codigo:'PR000089', nombre:'Huang Cheng-Bang', alias:['Stan Huang'], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000089.webp'}, activo:true},
  {codigo:'PR000090', nombre:'Chen Hsuan-Yu', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000090.webp'}, activo:true},
  {codigo:'PR000091', nombre:'Chen Wei-Yeh', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000091.webp'}, activo:true},
  {codigo:'PR000092', nombre:'Huang Hung-Hsuan', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000092.webp'}, activo:true},
  {codigo:'PR000093', nombre:'Chang Jowei', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000093.webp'}, activo:true},
  {codigo:'PR000094', nombre:'Wu Ping-Chen', alias:['Roy Wu'], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000094.webp'}, activo:true},
  {codigo:'PR000095', nombre:'Huang Li-Feng', alias:['Leo Huang'], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000095.webp'}, activo:true},
  {codigo:'PR000096', nombre:'Lara Chen', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000096.webp'}, activo:true},
  {codigo:'PR000097', nombre:'Chou Yung-Hsuan', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000097.webp'}, activo:true},
  {codigo:'PR000098', nombre:'Tey Chia-Yi', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000098.webp'}, activo:true},
  {codigo:'PR000099', nombre:'Wang Ying-Yao', alias:[], pais:'TW', profesiones:['Actor'], multimedia:{foto:'PR000099.webp'}, activo:true},
  {codigo:'PR000100', nombre:'Wu Kai-Fei', alias:[], pais:'TW', profesiones:['Director'], multimedia:{foto:'PR000100.webp'}, activo:true},
  {codigo:'PR000101', nombre:'Chen Hung-Lu', alias:[], pais:'TW', profesiones:['Director'], multimedia:{foto:'PR000101.webp'}, activo:true},
  {codigo:'PR000102', nombre:'Lian Yu-Zhe', alias:[], pais:'TW', profesiones:['Director'], multimedia:{foto:'PR000102.webp'}, activo:true},
  {codigo:'PR000103', nombre:'Tsai Fei-Chiao', alias:[], pais:'TW', profesiones:['Guionista'], multimedia:{foto:'PR000103.webp'}, activo:true},
  {codigo:'PR000104', nombre:'Lin Bei-Xuan', alias:[], pais:'TW', profesiones:['Guionista'], multimedia:{foto:'PR000104.webp'}, activo:true},
  {codigo:'PR000105', nombre:'Lin Yun-Hsiang', alias:[], pais:'TW', profesiones:['Guionista'], multimedia:{foto:'PR000105.webp'}, activo:true},
  {codigo:'PR000106', nombre:'Xiao Yi-Wei', alias:[], pais:'TW', profesiones:['Guionista'], multimedia:{foto:'PR000106.webp'}, activo:true},
  {codigo:'PR000107', nombre:'Chen Liang-Ci', alias:[], pais:'TW', profesiones:['Guionista'], multimedia:{foto:'PR000107.webp'}, activo:true},
  {codigo:'PR000108', nombre:'Boss Chaikamon Sermsongwittaya', alias:['Boss'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000108.webp'}, activo:true},
  {codigo:'PR000109', nombre:'Noeul Nuttarat Tangwai', alias:['Noeul'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000109.webp'}, activo:true},
  {codigo:'PR000110', nombre:'Fort Thitipong Sengngai', alias:['Fort'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000110.webp'}, activo:true},
  {codigo:'PR000111', nombre:'Peat Wasuthorn Chaijinda', alias:['Peat'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000111.webp'}, activo:true},
  {codigo:'PR000112', nombre:'Tonnam Piamchon Damrongsunthornchai', alias:['Tonnam'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000112.webp'}, activo:true},
  {codigo:'PR000113', nombre:'Nattapong Prompinit', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000113.webp'}, activo:true},
  {codigo:'PR000114', nombre:'Pepper Pongpat Unhapipatpong', alias:['Pepper'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000114.webp'}, activo:true},
  {codigo:'PR000115', nombre:'Sujitra Hemhiran', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000115.webp'}, activo:true},
  {codigo:'PR000116', nombre:'Nut Phattaraporn Pengsuk', alias:['Nut'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000116.webp'}, activo:true},
  {codigo:'PR000117', nombre:'Krismon Thanawat Sutthijaroen', alias:['Krismon'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000117.webp'}, activo:true},
  {codigo:'PR000118', nombre:'Theme Phubeth Atarunwong', alias:['Theme'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000118.webp'}, activo:true},
  {codigo:'PR000119', nombre:'Dunk Patak Pingmuang', alias:['Dunk'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000119.webp'}, activo:true},
  {codigo:'PR000120', nombre:'Holland Apsaralaila Pechploychomphu', alias:['Holland'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000120.webp'}, activo:true},
  {codigo:'PR000121', nombre:'Daniel Alex Bird', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000121.webp'}, activo:true},
  {codigo:'PR000122', nombre:'Peach Peachawit Phetthanakul', alias:['Peach'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000122.webp'}, activo:true},
  {codigo:'PR000123', nombre:'Lerm Chalermsak Yamchamang', alias:['Lerm'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000123.webp'}, activo:true},
  {codigo:'PR000124', nombre:'Cartoon Benyapon Chimsud', alias:['Cartoon'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000124.webp'}, activo:true},
  {codigo:'PR000125', nombre:'Zani Nipaporn Thititanakarn', alias:['Zani'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000125.webp'}, activo:true},
  {codigo:'PR000126', nombre:'Sunny Wannarat Wattadalimma', alias:['Sunny'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000126.webp'}, activo:true},
  {codigo:'PR000127', nombre:'Pak Naphat Leelahatorn', alias:['Pak'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000127.webp'}, activo:true},
  {codigo:'PR000128', nombre:'Aya Orapan Phongmaykin', alias:['Aya'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000128.webp'}, activo:true},
  {codigo:'PR000129', nombre:'Kate Sasisarun Phiboonrattapong', alias:['Kate'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000129.webp'}, activo:true},
  {codigo:'PR000130', nombre:'Forth Kashane Pichetsopon', alias:['Forth'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000130.webp'}, activo:true},
  {codigo:'PR000131', nombre:'Donut Suppawit Thongyuen', alias:['Donut'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000131.webp'}, activo:true},
  {codigo:'PR000132', nombre:'Akamsiri Suwannasuk', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000132.webp'}, activo:true},
  {codigo:'PR000133', nombre:'Pintira Singhaseem', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000133.webp'}, activo:true},
  {codigo:'PR000134', nombre:'Neti Suwanjinda', alias:['Ne'], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000134.webp'}, activo:true},
  {codigo:'PR000135', nombre:'May Orawan Vichayawannak', alias:['MAME'], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000135.webp'}, activo:true},
  {codigo:'PR000136', nombre:'Win Achawin Michaels', alias:['Win'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000136.webp'}, activo:true},
  {codigo:'PR000137', nombre:'Folk Thitiphat Chankaew', alias:['Folk'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000137.webp'}, activo:true},
  {codigo:'PR000138', nombre:'War Wanarat Ratsameerat', alias:['War'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000138.webp'}, activo:true},
  {codigo:'PR000139', nombre:'Yin Anan Wong', alias:['Yin'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000139.webp'}, activo:true},
  {codigo:'PR000140', nombre:'Prom Ratchapat Worrasarn', alias:['Prom'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000140.webp'}, activo:true},
  {codigo:'PR000141', nombre:'Ormsin Supitcha Limsommut', alias:['Ormsin'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000141.webp'}, activo:true},
  {codigo:'PR000142', nombre:'Thamrong Cunpisut', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000142.webp'}, activo:true},
  {codigo:'PR000143', nombre:'Saran Naksodsi', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000143.webp'}, activo:true},
  {codigo:'PR000144', nombre:'Prat Itthichaicharoen', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000144.webp'}, activo:true},
  {codigo:'PR000145', nombre:'Aomsin Wongrapee Krusong', alias:['Aomsin'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000145.webp'}, activo:true},
  {codigo:'PR000146', nombre:'Donut Patipat Chaipornkaew', alias:['Donut'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000146.webp'}, activo:true},
  {codigo:'PR000147', nombre:'Patsapon Jansuppakitkun', alias:['Bever'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000147.webp'}, activo:true},
  {codigo:'PR000148', nombre:'Nontawat Kumleung', alias:['Com'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000148.webp'}, activo:true},
  {codigo:'PR000149', nombre:'Thanakom Minthananan', alias:['Win'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000149.webp'}, activo:true},
  {codigo:'PR000150', nombre:'Thammasiri Umpujh', alias:['Frong'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000150.webp'}, activo:true},
  {codigo:'PR000151', nombre:'Benz Atthanin Thaninphanuwiwat', alias:['Benz'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000151.webp'}, activo:true},
  {codigo:'PR000152', nombre:'Tayiga Uawannachotima', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000152.webp'}, activo:true},
  {codigo:'PR000153', nombre:'Thitichaya Chiwpreecha', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000153.webp'}, activo:true},
  {codigo:'PR000154', nombre:'Kasidej Hongladaromp', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000154.webp'}, activo:true},
  {codigo:'PR000155', nombre:'Nantalit Tampacha', alias:[], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000155.webp'}, activo:true},
  {codigo:'PR000156', nombre:'Karnpicha Sinlertpattana', alias:[], pais:'TH', profesiones:['Director','Guionista'], multimedia:{foto:'PR000156.webp'}, activo:true},
  {codigo:'PR000157', nombre:'Natthapat Chanchaisombat', alias:['Boom'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000157.webp'}, activo:true},
  {codigo:'PR000158', nombre:'Phadung Samajarn', alias:['Lit'], pais:'TH', profesiones:['Director','Guionista'], multimedia:{foto:'PR000158.webp'}, activo:true},
  {codigo:'PR000159', nombre:'Pongpisit Botsri', alias:['Kitt Botta'], pais:'TH', profesiones:['Director','Guionista'], multimedia:{foto:'PR000159.webp'}, activo:true},
  {codigo:'PR000160', nombre:'Chiangmun Ngamkanokwan', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000160.webp'}, activo:true},
  {codigo:'PR000161', nombre:'Nakarin Narkpreecha', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000161.webp'}, activo:true},
  {codigo:'PR000162', nombre:'Perawat Sangpotirat', alias:['Krist'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000162.webp'}, activo:true},
  {codigo:'PR000163', nombre:'Prachaya Ruangroj', alias:['Singto'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000163.webp'}, activo:true},
  {codigo:'PR000164', nombre:'Thitipoom Techaapaikhun', alias:['New'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000164.webp'}, activo:true},
  {codigo:'PR000165', nombre:'Korn Khunatipapisiri', alias:['Oaujun'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000165.webp'}, activo:true},
  {codigo:'PR000166', nombre:'Pattadon Janngeon', alias:['Fiat'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000166.webp'}, activo:true},
  {codigo:'PR000167', nombre:'Krittanai Arsalprakit', alias:['Nammon'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000167.webp'}, activo:true},
  {codigo:'PR000168', nombre:'Kunchanuj Kengkarnka', alias:['Kun'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000168.webp'}, activo:true},
  {codigo:'PR000169', nombre:'Oranicha Krinchai', alias:['Proud'], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000169.webp'}, activo:true},
  {codigo:'PR000170', nombre:'Napasorn Weerayuttvilai', alias:['Puimek'], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000170.webp'}, activo:true},
  {codigo:'PR000171', nombre:'Nachat Juntapun', alias:['Nicky'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000171.webp'}, activo:true},
  {codigo:'PR000172', nombre:'Korawit Boonsri', alias:['Gun'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000172.webp'}, activo:true},
  {codigo:'PR000173', nombre:'Suttatip Wutchaipradit', alias:['Ampere'], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000173.webp'}, activo:true},
  {codigo:'PR000174', nombre:'Nararak Jaibumrung', alias:['Ten'], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000174.webp'}, activo:true},
  {codigo:'PR000175', nombre:'Teerapat Lohanan', alias:['Fluke'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000175.webp'}, activo:true},
  {codigo:'PR000176', nombre:'Ittikorn Kraicharoen', alias:['Ice'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000176.webp'}, activo:true},
  {codigo:'PR000177', nombre:'Jumpol Adulkittiporn', alias:['Off'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000177.webp'}, activo:true},
  {codigo:'PR000178', nombre:'Natthawaranthorn Khamchoo', alias:['Onew'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000178.webp'}, activo:true},
  {codigo:'PR000179', nombre:'Ployshompoo Supasap', alias:['Jan'], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000179.webp'}, activo:true},
  {codigo:'PR000180', nombre:'Maripha Siripool', alias:['Wawa'], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000180.webp'}, activo:true},
  {codigo:'PR000181', nombre:'Naradon Namboonjit', alias:['Prince'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000181.webp'}, activo:true},
  {codigo:'PR000182', nombre:'Patipan Intrakul', alias:['Makbook'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000182.webp'}, activo:true},
  {codigo:'PR000183', nombre:'Phurin Ruangvivatjarus', alias:['M'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000183.webp'}, activo:true},
  {codigo:'PR000184', nombre:'Patcharin Thongyangyuen', alias:[], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000184.webp'}, activo:true},
  {codigo:'PR000185', nombre:'Boochita Pitakard', alias:[], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000185.webp'}, activo:true},
  {codigo:'PR000186', nombre:'Worakamon Nokkaew', alias:[], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000186.webp'}, activo:true},
  {codigo:'PR000187', nombre:'Pongpol Saneewong Na Ayutaya', alias:['Arm'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000187.webp'}, activo:true},
  {codigo:'PR000188', nombre:'Pitiwat Chaimongkol', alias:['Aor'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000188.webp'}, activo:true},
  {codigo:'PR000189', nombre:'Alysaya Tsoi', alias:['Alice'], pais:'TH', profesiones:['Actriz'], multimedia:{foto:'PR000189.webp'}, activo:true},
  {codigo:'PR000190', nombre:'Thanapas Suttichannapa', alias:['M'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000190.webp'}, activo:true},
  {codigo:'PR000191', nombre:'Tanapon Sukumpantanasan', alias:['Perth'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000191.webp'}, activo:true},
  {codigo:'PR000192', nombre:'Suppapong Udomkaewkanjana', alias:['Saint'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000192.webp'}, activo:true},
  {codigo:'PR000193', nombre:'Rathavit Kijworalak', alias:['Plan'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000193.webp'}, activo:true},
  {codigo:'PR000194', nombre:'Napat Na Ranong', alias:['Gun'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000194.webp'}, activo:true},
  {codigo:'PR000195', nombre:'Siwat Jumlongkul', alias:['Mark'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000195.webp'}, activo:true},
  {codigo:'PR000196', nombre:'Kirati Puangmalee', alias:['Title'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000196.webp'}, activo:true},
  {codigo:'PR000197', nombre:'Nachjaree Horvejkul', alias:['Cherreen'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000197.webp'}, activo:true},
  {codigo:'PR000198', nombre:'Pirapat Watthanasetsiri', alias:['Earth'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000198.webp'}, activo:true},
  {codigo:'PR000199', nombre:'Preya Wongrabeb', alias:['Mam'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000199.webp'}, activo:true},
  {codigo:'PR000200', nombre:'Apasiri Nitibhon', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000200.webp'}, activo:true},
  {codigo:'PR000201', nombre:'Chutima Teepanat', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000201.webp'}, activo:true},
{codigo:'PR000202', nombre:'Witawat Singlampong', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000202.webp'}, activo:true},
{codigo:'PR000203', nombre:'Kris Songsamphant', alias:['Kris'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000203.webp'}, activo:true},
{codigo:'PR000204', nombre:'Praphatthorn Chakkhuchan', alias:['James'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000204.webp'}, activo:true},
{codigo:'PR000205', nombre:'Channanda Chieovisaman', alias:['Ew'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000205.webp'}, activo:true},
{codigo:'PR000206', nombre:'Mudchima Pluempitiviriyavaj', alias:['Bua'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000206.webp'}, activo:true},
{codigo:'PR000207', nombre:'Praeploy Oree', alias:['Prae'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000207.webp'}, activo:true},
{codigo:'PR000208', nombre:'Thanaboon Wanlopsirinan', alias:['Na'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000208.webp'}, activo:true},
{codigo:'PR000209', nombre:'Chonwari Chutiwatkhotrachai', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000209.webp'}, activo:true},
{codigo:'PR000210', nombre:'Nichakoon Khajornborirak', alias:['Meen'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000210.webp'}, activo:true},
{codigo:'PR000211', nombre:'Est Supha Sangaworawong', alias:['Est'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000211.webp'}, activo:true},
{codigo:'PR000212', nombre:'Pisitpon Ekpongpisit', alias:['Jump'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000212.webp'}, activo:true},
{codigo:'PR000213', nombre:'Krittin Sosungnern', alias:['Krit'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000213.webp'}, activo:true},
{codigo:'PR000214', nombre:'Thapanat Athikompokin', alias:['Boss'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000214.webp'}, activo:true},
{codigo:'PR000215', nombre:'Norravit Songtrai', alias:['Buzz'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000215.webp'}, activo:true},
{codigo:'PR000216', nombre:'Thawatchai Phechsuk', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000216.webp'}, activo:true},
{codigo:'PR000217', nombre:'Pisit Mahatthanajatuphat', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000217.webp'}, activo:true},
{codigo:'PR000218', nombre:'Rene Lannaphat Sooyacheewin', alias:['Rene'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000218.webp'}, activo:true},
{codigo:'PR000219', nombre:'Thitipat Pookbooncherd', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000219.webp'}, activo:true},
{codigo:'PR000220', nombre:'Janya Thanasawangkul', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000220.webp'}, activo:true},
{codigo:'PR000221', nombre:'Tinnapat Tinnakorn', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000221.webp'}, activo:true},
{codigo:'PR000222', nombre:'Guy Pakin Nantajiwakornchai', alias:['Guy'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000222.webp'}, activo:true},
{codigo:'PR000223', nombre:'Max Phongsathron Cheewatham', alias:['Max'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000223.webp'}, activo:true},
{codigo:'PR000224', nombre:'Suppasit Jongcheveevat', alias:['Mew'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000224.webp'}, activo:true},
{codigo:'PR000225', nombre:'Kanawut Traipipattanapong', alias:['Gulf'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000225.webp'}, activo:true},
{codigo:'PR000226', nombre:'Suttinut Uengtrakul', alias:['Mild'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000226.webp'}, activo:true},
{codigo:'PR000227', nombre:'Kittipat Kaewcharoen', alias:['Kaownah'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000227.webp'}, activo:true},
{codigo:'PR000228', nombre:'Natthad Kunakornkiat', alias:['Hiter'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000228.webp'}, activo:true},
{codigo:'PR000229', nombre:'Parinya Angsanan', alias:['Kokliang'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000229.webp'}, activo:true},
{codigo:'PR000230', nombre:'Napat Srinakluan', alias:['Boat'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000230.webp'}, activo:true},
{codigo:'PR000231', nombre:'Thanayut Thakoonauttaya', alias:['Tong'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000231.webp'}, activo:true},
{codigo:'PR000232', nombre:'Tanawin Duangnate', alias:['Mawin'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000232.webp'}, activo:true},
{codigo:'PR000233', nombre:'Kantheephop Sirorattanaphanit', alias:['Run'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000233.webp'}, activo:true},
{codigo:'PR000234', nombre:'Wasin Panunaporn', alias:['Kenji'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000234.webp'}, activo:true},
{codigo:'PR000235', nombre:'Pongkorn Wongkrittiyarat', alias:['Kaprao'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000235.webp'}, activo:true},
{codigo:'PR000236', nombre:'Pattarabut Kiennukul', alias:['AA'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000236.webp'}, activo:true},
{codigo:'PR000237', nombre:'Siwapohn Langkapin', alias:['Eye'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000237.webp'}, activo:true},
{codigo:'PR000238', nombre:'Usuki Ayuta', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000238.webp'}, activo:true},
{codigo:'PR000239', nombre:'Suthisak Akarapanuwittaya', alias:['Mac'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000239.webp'}, activo:true},
{codigo:'PR000240', nombre:'Khongkao Premsirinithikun', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000240.webp'}, activo:true},
{codigo:'PR000241', nombre:'Penkawin Wangniwetkul', alias:['Ice'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000241.webp'}, activo:true},
{codigo:'PR000242', nombre:'Natthapong Kanthathan', alias:['Khawoat'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000242.webp'}, activo:true},
{codigo:'PR000243', nombre:'Thaweesak Alexander Thananan', alias:['Alexander'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000243.webp'}, activo:true},
{codigo:'PR000244', nombre:'Sarocha Watitapun', alias:['Tao'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000244.webp'}, activo:true},
{codigo:'PR000245', nombre:'Thanayong Wongtrakul', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000245.webp'}, activo:true},
{codigo:'PR000246', nombre:'Ampha Phoosit', alias:['Aew'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000246.webp'}, activo:true},
{codigo:'PR000247', nombre:'Tiprada Maier', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000247.webp'}, activo:true},
{codigo:'PR000248', nombre:'Chalongrat Novsamrong', alias:['First'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000248.webp'}, activo:true},
{codigo:'PR000249', nombre:'Phat Prayunviwat', alias:['Jame'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000249.webp'}, activo:true},
{codigo:'PR000250', nombre:'Tanatorn Saenangkanikorn', alias:['Title'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000250.webp'}, activo:true},
{codigo:'PR000251', nombre:'Sarunsathorn Tanawatcharawat', alias:['Haii'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000251.webp'}, activo:true},
{codigo:'PR000252', nombre:'Rebecca Patricia Armstrong', alias:['Becky'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000252.webp'}, activo:true},
{codigo:'PR000253', nombre:'Vivid Bavornkiratikajorn', alias:['Tee'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000253.webp'}, activo:true},
{codigo:'PR000254', nombre:'Petchpailin Chitcharoon', alias:['Name'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000254.webp'}, activo:true},
{codigo:'PR000255', nombre:'Thanakorn Sangwan', alias:['Ole'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000255.webp'}, activo:true},
{codigo:'PR000256', nombre:'Natcha Somboonwong', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000256.webp'}, activo:true},
{codigo:'PR000257', nombre:'Bundit Sintanaparadee', alias:['Tee'], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000257.webp'}, activo:true},
{codigo:'PR000258', nombre:'Passawut Sukbua', alias:['Pique'], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000258.webp'}, activo:true},
{codigo:'PR000259', nombre:'Vichayaporn Sukkul', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000259.webp'}, activo:true},
{codigo:'PR000260', nombre:'Wanna Kortunyavat', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000260.webp'}, activo:true},
{codigo:'PR000261', nombre:'Achirawich Saliwattana', alias:['Gun'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000261.webp'}, activo:true},
{codigo:'PR000262', nombre:'Rutricha Phapakithi', alias:['Ciize','Apichaya Saejung'], pais:'TH', profesiones:['Actor','Cantante'], multimedia:{foto:'PR000262.webp'}, activo:true},
{codigo:'PR000263', nombre:'Benja Singkharawat', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000263.webp'}, activo:true},
{codigo:'PR000264', nombre:'Chamaphan Phanachotiwat', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000264.webp'}, activo:true},
{codigo:'PR000265', nombre:'Chatkaew Susiwa', alias:[], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000265.webp'}, activo:true},
{codigo:'PR000266', nombre:'Chayapol Jutamas', alias:['AJ'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000266.webp'}, activo:true},
{codigo:'PR000267', nombre:'Chutavuth Pattarakampol', alias:['March'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000267.webp'}, activo:true},
{codigo:'PR000268', nombre:'Gawin Caskey', alias:['Fluke'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000268.webp'}, activo:true},
{codigo:'PR000269', nombre:'Jintanutda Lummakanon', alias:['Pango'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000269.webp'}, activo:true},
{codigo:'PR000270', nombre:'Jirakit Thawornwong', alias:['Mek'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000270.webp'}, activo:true},
{codigo:'PR000271', nombre:'Juthapich Indrajundra', alias:['Jamie'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000271.webp'}, activo:true},
{codigo:'PR000272', nombre:'Kaimook Apasiri Kittithanon', alias:['Kaimook'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000272.webp'}, activo:true},
{codigo:'PR000273', nombre:'Kanyawee Songmuang', alias:['Thanaerng'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000273.webp'}, activo:true},
{codigo:'PR000274', nombre:'Krittaphat Chanthanaphot', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000274.webp'}, activo:true},
{codigo:'PR000275', nombre:'Kullapat Klatanakan', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000275.webp'}, activo:true},
{codigo:'PR000276', nombre:'Lapassalan Jiravechsoontornkul', alias:['Mild'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000276.webp'}, activo:true},
{codigo:'PR000277', nombre:'Lapisara Intarasut', alias:['Apple'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000277.webp'}, activo:true},
{codigo:'PR000278', nombre:'Natticha Chantaravareelekha', alias:['Fond'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000278.webp'}, activo:true},
{codigo:'PR000279', nombre:'Noppharnach Chaiwimol', alias:['Aof','Backaof','Noppharnach Chaiyahwimhon'], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000279.webp'}, activo:true},
{codigo:'PR000280', nombre:'Noelle Klinnium', alias:['Tiny'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000280.webp'}, activo:true},
{codigo:'PR000281', nombre:'Phakjira Kanrattanasoot', alias:['Nanan'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000281.webp'}, activo:true},
{codigo:'PR000282', nombre:'Ploynira Hiruntaveesin', alias:['Kapook','Phatchara Thabthong','Phatchara Tubthong'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000282.webp'}, activo:true},
{codigo:'PR000283', nombre:'Phurikulkrit Chusakdiskulwibul', alias:['Amp'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000283.webp'}, activo:true},
{codigo:'PR000284', nombre:'Phuwin Tangsakyuen', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000284.webp'}, activo:true},
{codigo:'PR000285', nombre:'Pluem Pongpisal', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000285.webp'}, activo:true},
{codigo:'PR000286', nombre:'Pop Khamgasem', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000286.webp'}, activo:true},
{codigo:'PR000287', nombre:'Rachanun Mahawan', alias:['Film'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000287.webp'}, activo:true},
{codigo:'PR000288', nombre:'Saitharn Niyomkarn', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000288.webp'}, activo:true},
{codigo:'PR000289', nombre:'Sananthachat Thanapatpisal', alias:['Fon'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000289.webp'}, activo:true},
{codigo:'PR000290', nombre:'Sattaphong Phiangphor', alias:['Tao'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000290.webp'}, activo:true},
{codigo:'PR000291', nombre:'Suphakorn Sriphothong', alias:['Pod'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000291.webp'}, activo:true},
{codigo:'PR000292', nombre:'Tawan Vihokratana', alias:['Tay'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000292.webp'}, activo:true},
{codigo:'PR000293', nombre:'Tanutchai Wijitvongtong', alias:['Mond'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000293.webp'}, activo:true},
{codigo:'PR000294', nombre:'Trai Nimtawat', alias:['Neo'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000294.webp'}, activo:true},
{codigo:'PR000295', nombre:'Worranit Thawornwong', alias:['Mook'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000295.webp'}, activo:true},
{codigo:'PR000296', nombre:'Nirattisai Ratphithak', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000296.webp'}, activo:true},
{codigo:'PR000297', nombre:'Sengahloune Wannaju', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000297.webp'}, activo:true},
{codigo:'PR000298', nombre:'Chisanupong Puangmanee', alias:['Smart'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000298.webp'}, activo:true},
{codigo:'PR000299', nombre:'Pongsapak Rachaporn', alias:['James'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000299.webp'}, activo:true},
{codigo:'PR000300', nombre:'Supakit Wilasmongkolchai', alias:['Chai'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000300.webp'}, activo:true},
{codigo:'PR000301', nombre:'Supachok Wilasmongkolchai', alias:['Seng'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000301.webp'}, activo:true},
{codigo:'PR000302', nombre:'Putthanat Chayaaphinanthakul', alias:['Puth'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000302.webp'}, activo:true},
{codigo:'PR000303', nombre:'Phunthida Phairuangkij', alias:['Beam'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000303.webp'}, activo:true},
{codigo:'PR000304', nombre:'Sirinya Puengsuwan', alias:['Rin'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000304.webp'}, activo:true},
{codigo:'PR000305', nombre:'Nattawut Praphapensuk', alias:['Earth'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000305.webp'}, activo:true},
{codigo:'PR000306', nombre:'Parlika Mongkonlirwrungfa', alias:['Earth'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000306.webp'}, activo:true},
{codigo:'PR000307', nombre:'Jakkarin Yungnun', alias:['Natt'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000307.webp'}, activo:true},

{codigo:'PR000308', nombre:'Natasitt Uareksit', alias:['Nat'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000308.webp'}, activo:true},
{codigo:'PR000309', nombre:'Kornthas Rujeerattanavorapan', alias:['Max'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000309.webp'}, activo:true},
{codigo:'PR000310', nombre:'Talay Sanguandikul', alias:['Lay'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000310.webp'}, activo:true},
{codigo:'PR000311', nombre:'Phusanu Wongsavanischakorn', alias:['Yoon'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000311.webp'}, activo:true},
{codigo:'PR000312', nombre:'Karn Kritsanaphan', alias:['Jimmy'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000312.webp'}, activo:true},
{codigo:'PR000313', nombre:'Sittichok Pueakpoolpol', alias:['Tommy'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000313.webp'}, activo:true},
{codigo:'PR000314', nombre:'Panuwat Kerdthongtavee', alias:['Copter'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000314.webp'}, activo:true},
{codigo:'PR000315', nombre:'Warodom Khemmonta', alias:['Kimmon'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000315.webp'}, activo:true},

{codigo:'PR000316', nombre:'Teshin Anusananan', alias:['Title'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000316.webp'}, activo:true},
{codigo:'PR000317', nombre:'Supakrit Charoonmatha', alias:['Man'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000317.webp'}, activo:true},
{codigo:'PR000318', nombre:'Anna Chuancheun', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000318.webp'}, activo:true},
{codigo:'PR000319', nombre:'Puttachat Pongsuchat', alias:['Tui'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000319.webp'}, activo:true},
{codigo:'PR000320', nombre:'Punyawee Sukkulworasate', alias:['Po'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000320.webp'}, activo:true},
{codigo:'PR000321', nombre:'Chollatorn Pratchyaroongroj', alias:['Jam'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000321.webp'}, activo:true},
{codigo:'PR000322', nombre:'Suphach Tawsagun', alias:['Boky'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000322.webp'}, activo:true},
{codigo:'PR000323', nombre:'Sasit Chatpiroonpun', alias:['Ramil'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000323.webp'}, activo:true},
{codigo:'PR000324', nombre:'Jumpol Thongtan', alias:['Gokhai'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000324.webp'}, activo:true},

{codigo:'PR000325', nombre:'Kavinpat Thanahiransilp', alias:['Jo'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000325.webp'}, activo:true},
{codigo:'PR000326', nombre:'Peerawat Sareewong', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000326.webp'}, activo:true},
{codigo:'PR000327', nombre:'Warinda Damrongphol', alias:['Dada'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000327.webp'}, activo:true},
{codigo:'PR000328', nombre:'Thongthong Mokjok', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000328.webp'}, activo:true},
{codigo:'PR000329', nombre:'Korkuer Deewattananukul', alias:['Yo'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000329.webp'}, activo:true},
{codigo:'PR000330', nombre:'Apisara Koetchuchuen', alias:['Dao'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000330.webp'}, activo:true},
{codigo:'PR000331', nombre:'Krittaporn Thorangkul', alias:['Film'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000331.webp'}, activo:true},
{codigo:'PR000332', nombre:'Benjamin Brasier', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000332.webp'}, activo:true},
{codigo:'PR000333', nombre:'Pinyadar Salinvarradar', alias:['Nitta'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000333.webp'}, activo:true},
{codigo:'PR000334', nombre:'Prarunyu Sooksamran', alias:['Ken'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000334.webp'}, activo:true},
{codigo:'PR000335', nombre:'Natapoj Tanatip-Udomchok', alias:['Best'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000335.webp'}, activo:true},
{codigo:'PR000336', nombre:'Thanapat Koprasertthaworn', alias:['Phat'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000336.webp'}, activo:true},
{codigo:'PR000337', nombre:'Duangta Toongkamanee', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000337.webp'}, activo:true},
{codigo:'PR000338', nombre:'Phanudet Watnasuchart', alias:[], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000338.webp'}, activo:true},
{codigo:'PR000339', nombre:'Chacree Rujiviphat', alias:[], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000339.webp'}, activo:true},
{codigo:'PR000340', nombre:'Piangpaitoon Satrawaha', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000340.webp'}, activo:true},
{codigo:'PR000341', nombre:'Sadanan Somatchariyakun', alias:[], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000341.webp'}, activo:true},
{codigo:'PR000342', nombre:'Nipitpon Muangsinun', alias:[], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000342.webp'}, activo:true},
{codigo:'PR000343', nombre:'Nutthakorn Phorntiramongkol', alias:['Nutt'], pais:'TH', profesiones:['Guionista'], multimedia:{foto:'PR000343.webp'}, activo:true},
{codigo:'PR000344', nombre:'David Bigander', alias:[], pais:'TH', profesiones:['Director'], multimedia:{foto:'PR000344.webp'}, activo:true},
{codigo:'PR000345', nombre:'Phattharawan Panitcha', alias:['Chompu'], pais:'TH', profesiones:['Actor'], multimedia:{foto:'PR000339.webp'}, activo:true},
{codigo:'PR000346', nombre:'Chomanai', nombreOriginal:'ชมณัย', alias:[], pais:'TH', idioma:'th', profesiones:['Guionista'], multimedia:{foto:'PR000346.webp'}, activo:true},
  {codigo:'PR000347', nombre:'Lee Long Shi', nombreOriginal:'李龙世', alias:['Long'], pais:'SG', idioma:'th', fechaNacimiento:'2000-08-07', lugarNacimiento:'Singapore', fallecimiento:'', profesiones:['Actor'], multimedia:{foto:'PR000347.webp'}, activo:true},
  
  {codigo:'PR000348', nombre:'Tae Darvid Kreepolrerk', nombreOriginal:'ดาวิชญ์ กรีพลฤกษ์', nombreOrden:'Kreepolrerk, Tae Darvid', alias:['Tae'], pais:'TH', idioma:'th', fechaNacimiento:'1990-12-26', lugarNacimiento:'Bangkok, Tailandia', profesiones:['Actor','Modelo','Cantante'], redes:{instagram:'tae_darvid',x:'tae_darvid'}, activo:true},
{codigo:'PR000349', nombre:'Shane Nutchapol Cheevapanyaroj', nombreOriginal:'ณัชชาภ ชีวะพันธ์ยาโรย', nombreOrden:'Cheevapanyaroj, Shane Nutchapol', alias:['Shane','Rojanin Kulphatthanaphon'], pais:'TH', idioma:'th', fechaNacimiento:'1997-08-04', profesiones:['Actor'], redes:{instagram:'shanerler',x:'Shanerler',tiktok:'shanerler'}, activo:true},
{codigo:'PR000350', nombre:'Kit Ronnakit Tantiwilai', nombreOriginal:'กฤต รณกฤต ตันติวิไล', nombreOrden:'Tantiwilai, Kit Ronnakit', alias:['Kit'], pais:'TH', idioma:'th', profesiones:['Actor'], redes:{instagram:'kit_ronnakit'}, activo:true},
{codigo:'PR000351', nombre:'Tang Chinadis Weangwises', nombreOriginal:'ชินดิศ เวียงวิเศษ', nombreOrden:'Weangwises, Tang Chinadis', alias:['Tang'], pais:'TH', idioma:'th', fechaNacimiento:'1999-03-12', profesiones:['Actor','Cantante'], redes:{instagram:'chinadis',tiktok:'shinadis'}, activo:true},
{codigo:'PR000352', nombre:'Mai Jirawat Vongdilokvath', nombreOriginal:'จิรวัฒน์ วงศ์ดิลกวัฒน์', nombreOrden:'Vongdilokvath, Mai Jirawat', alias:['Mai'], pais:'TH', idioma:'th', profesiones:['Actor'], activo:true},
{codigo:'PR000353', nombre:'Parn Thanaporn Wagprayoon', nombreOriginal:'ธนพร แวกประยูร', nombreOrden:'Wagprayoon, Parn Thanaporn', alias:['Parn'], pais:'TH', idioma:'th', fechaNacimiento:'1976-06-14', lugarNacimiento:'Thonburi, Bangkok, Tailandia', profesiones:['Actriz','Cantante'], redes:{instagram:'parnthanaporn'}, activo:true},
  {codigo:'PR000354', nombre:'Tichakorn Phukhaotong', nombreOriginal:'ทิชากร ภูเขาทอง', nombreOrden:'Phukhaotong, Tichakorn', alias:['Jojo'], pais:'TH', idioma:'th', fechaNacimiento:'1984-12-26', lugarNacimiento:'Surat Thani, Tailandia', profesiones:['Director','Guionista'], redes:{instagram:'jojo_tichakorn'}, activo:true},
];
